export const HomeProductList = [
    {
      id: 1,
      title: "OnePlus Nord 2 5G (Gray Sierra, 8GB RAM, 128GB Storage)",
      description: "",
      price: 28999,
      img: "https://m.media-amazon.com/images/I/71DL9xoLB9L._SX569_.jpg",
      quantity: 1,
    },
    {
      id: 2,
      title: "OnePlus Nord CE 2 Lite 5G (Blue Tide, 6GB RAM, 128GB Storage)",
      description: "",
      price: 19999,
      img: "https://m.media-amazon.com/images/I/71AvQd3VzqL._SX425_.jpg",
      quantity: 1,
    },
    {
      id: 3,
      title: "Samsung Galaxy S21 5G (Phantom Violet, 8GB, 128GB Storage)",
      description: "",
      price: 57999,
      img: "https://m.media-amazon.com/images/I/91EA08YkYgL._SY445_.jpg",
      quantity: 1,
    },
    {
      id: 4,
      title: "Apple iPhone 13 (128GB) - Blue",
      description: "",
      price: 71990,
      img: "https://m.media-amazon.com/images/I/71xb2xkN5qL._SX466_.jpg",
      quantity: 1,
    },
    {
      id: 5,
      title: "Apple iPhone 12 (64GB) - Blue",
      description: "",
      price: 54999,
      img: "https://m.media-amazon.com/images/I/71ZOtNdaZCL._SX522_.jpg",
      quantity: 1,
    },
    {
      id: 6,
      title: "Redmi Note 10S (Cosmic Purple, 6GB RAM, 64GB Storage) -Super Amoled Display | 33W Charger Included",
      description: "",
      price: 12999,
      img: "https://m.media-amazon.com/images/I/81sZamLSPWL._SX425_.jpg",
      quantity: 1,
    },
    {
      id: 7,
      title: "Redmi Note 10T 5G (Graphite Black, 4GB RAM, 64GB Storage) | Dual5G | 90Hz Adaptive Refresh Rate | MediaTek Dimensity 700 7nm Processor | 22.5W Charger",
      description: "",
      price: 11999,
      img: "https://m.media-amazon.com/images/I/81oFpnDM2EL._SX425_.jpg",
      quantity: 1,
    },
    {
      id: 8,
      title: "vivo iQOO Z3 5G (Cyber Blue, 8GB RAM, 128GB Storage) | India's First SD 768G 5G Processor | 55W FlashCharge",
      description: "",
      price: 20999,
      img: "https://images-eu.ssl-images-amazon.com/images/I/41LRLdVQvBS._SX300_SY300_QL70_FMwebp_.jpg",
      quantity: 1,
    },
    {
      id: 9,
      title: "iQOO 7 5G (Storm Black, 8GB RAM, 128GB Storage) | 3GB Extended RAM",
      description: "",
      price: 29990,
      img: "https://m.media-amazon.com/images/I/51OvvRTnJTS._SX425_.jpg",
      quantity: 1,
    },
    {
      id: 10,
      title: "MOTOROLA g42 (Atlantic Green, 64 GB)  (4 GB RAM)",
      description: "",
      price: 13999,
      img: "https://rukminim1.flixcart.com/image/416/416/l51d30w0/mobile/n/y/v/-original-imagfsuftgdf6jxe.jpeg?q=70",
      quantity: 1,
    },
    {
      id: 11,
      title: "MOTOROLA g42 (Metallic Rose, 64 GB)  (4 GB RAM)",
      description: "",
      price: 13999,
      img: "https://rukminim1.flixcart.com/image/416/416/l51d30w0/mobile/e/6/t/-original-imagfsufmgnfy8fw.jpeg?q=70",
      quantity: 1,
    },
  ];